name: 'auto-version-build-number-update'
description: 'Updates the build number for ios and Android, aswell as the marketing version number.'
inputs:
  path-to-control-file: 
    description: 'The TSX file that holds the version-string and build numbers for iOS and Android.'
    required: true
    default: 'constants.tsx'


runs:
  using: "composite"
  steps:
    - name: Check the build string
      shell: bash
      run: python ${{github.action_path}}/scripts/CheckUpdate.py --tag ${GITHUB_REF#refs/*/} --version-file $INPUT_PATH_TO_CONTROL_FILE
     
    - name: Commit the changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Automatic build number update